# FROM php:8.1.9-fpm-alpine
# RUN apk --no-cache upgrade && \
#     apk --no-cache add bash git sudo openssh  libxml2-dev oniguruma-dev 
# autoconf gcc g++ make npm freetype-dev libjpeg-turbo-dev libpng-dev 
# libzip-dev





# # PHP: Install php extensions
# RUN pecl channel-update pecl.php.net
# RUN pecl install pcov ssh2 swoole
# RUN docker-php-ext-configure gd --with-freetype --with-jpeg
# RUN docker-php-ext-install mbstring xml  pcntl gd zip sockets pdo  
# pdo_mysql bcmath soap
# RUN docker-php-ext-enable mbstring xml gd  zip pcov pcntl sockets bcmath 
# pdo  pdo_mysql soap swoole


# RUN docker-php-ext-install pdo pdo_mysql sockets
# RUN curl -sS https://getcomposer.org/installer​ | php -- \
#      --install-dir=/usr/local/bin --filename=composer

# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# COPY --from=spiralscout/roadrunner:2.4.2 /usr/bin/rr /usr/bin/rr

# WORKDIR /app
# COPY . .

# RUN composer install
# RUN composer require laravel/octane spiral/roadrunner

# RUN npm install --global yarn
# RUN yarn
# RUN yarn prod


# RUN php artisan key:generate
# RUN php artisan migrate:refresh
# RUN php artisan db:seed
# RUN php artisan passport:install
# RUN php artisan passport:client --personal

# RUN php artisan octane:install --server="swoole"

# CMD php artisan octane:start --server="swoole" --host="0.0.0.0" 
# EXPOSE 8000

FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

RUN composer install
RUN composer require laravel/octane spiral/roadrunner

RUN npm install --global yarn
RUN yarn
RUN yarn prod


RUN php artisan key:generate
RUN php artisan migrate:refresh
RUN php artisan db:seed
RUN php artisan passport:install
RUN php artisan passport:client --personal

# Set working directory
WORKDIR /var/www

USER $user